version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
     - ./wordpress/wp-content/:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_PASSWORD: tomtom21

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8090:80
    volumes:
     - /sessions
    external_links:
     - db_server:mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tomtom21